project:
  type: website
  output-dir: docs
  # site-path: /drabdusinfo/

# Meta
description-meta: "Quarto Academic Website Template adapted by Dr. Gang He, further customized by Dr. Md Abdus Samad"
author-meta: "Dr. Md Abdus Samad"

website:
  title: "Md Abdus Samad"
  image: "https://quarto.org/quarto.png"
  description: "Quarto Academic Website Template adapted by Dr. Gang He, further customized by Dr. Md Abdus Samad"
 
  navbar:
    background: light  # You can change the background color here

    left:   # You can comment out all navigation items here if you just like to keep the index page only
#      - text: Home
#        href: index.qmd
      - text: About
        menu:
          - text: News
            href: posts.qmd#category=news
            # - text: Events
            # href: posts.qmd#category=event      
          - text: Contact
            href: contact.qmd 

      - text: Publications  
        href: publications60.qmd               
      # - text: Research
        # menu:
          # - text: List of Publications
            # href: publications60.qmd
          # - text: Selected Papers
            # href: posts.qmd#category=paper
          # - text: Grants
            # href: projects.qmd    

      - text: LaTeX 
        href: latex-guide.qmd

      # - text: Teaching # Comment the Teaching part out to remove the Teaching page
        # href: teaching.qmd
      # - text: Outreach
        # menu:        
        # - text: Presentations
          # href: posts.qmd#category=presentation 
      - text: Miscellaneous
        menu:
          - text: List of Publishers
            href: miscellaneous/publishers.qmd
          - text: Journal Templates
            href: miscellaneous/templates.qmd
          - text: Verifying Journal Indexing
            href: miscellaneous/indexing.qmd
          - text: Reference, Image Quality, and Detexify
            href: miscellaneous/reference.qmd
          - text: Author Services by Major Publishers
            href: miscellaneous/author-services.qmd
          - text: Document Conversion and Figure Tools
            href: miscellaneous/conversion.qmd
          - text: Manuscript Anonymization
            href: miscellaneous/anonymization.qmd
          - text: Switching Elsevier LaTeX Templates
            href: miscellaneous/elsevier.qmd
          - text: DOCX to LaTeX Convert
            href: miscellaneous/docx-latex.qmd
          - text: LaTeX Reference and Label Management
            href: miscellaneous/latex-reference.qmd
          - text: Latex Reference Converter
            href: miscellaneous/latex-converter.qmd
          - text: Sequential Section Labels
            href: miscellaneous/section-labels.qmd
          - text: Open Access Journals having Discount Policy
            href: miscellaneous/open-access.qmd
          - text: Overleaf git sync issues
            href: miscellaneous/overleaf.qmd
          - text: Latexdiff Configuration Guide
            href: miscellaneous/latexdiff.qmd
          - text: Open source tools
            href: miscellaneous/opensource.qmd
          - text: Windows shortcuts & commands
            href: miscellaneous/windows.qmd
          - text: Mathpix PDF to Word
            href: miscellaneous/mathpix.qmd
          - text: "Quarto Tips"
            href: miscellaneous/quarto-tips.qmd
          
      # - text: Group   # Comment the Group part out to remove the Group page
        # href: people.qmd

    right: 
      - text: CV
        href: files/nsf-biosketch.pdf
      # - icon: github
      #   href: https://github.com/drganghe/quarto-academic-website-template
      #   target: _blank
      - text: "{{< fa brands bluesky >}}"
        href: https://bsky.app
        target: _blank      
      - icon: rss
        href: posts.xml
        target: _blank
  
  page-navigation: true
  
  page-footer: 
   center: "Â© 2025 Dr. Md Abdus Samad. All rights reserved."
  #  right: "Built with Quarto"
    # left: "[Dr. Md Abdus Samad](http://www.github.com) &copy; <script>document.write(new Date().getFullYear())</script>" 
    # center: "Build on [Quart Academic Website Template](https://github.com/drganghe/quarto-academic-website-template) adapted by [Dr. Gang He](http://drganghe.github.io)"
    # right:  
    #   - icon: github
    #     href: https://github.com/drganghe/quarto-academic-website-template
    #     target: _blank
    #   - text: "{{< fa brands bluesky >}}" 
    #     href: https://bsky.app
    #     target: _blank
    #   - icon: rss
    #     href: posts.xml
    #     target: _blank  
  
  search:
    location: navbar
    type: textbox
  
  reader-mode: true

  draft-mode: unlinked
  
  # repo-url: https://github.com/drganghe/quarto-academic-website-template # commented by Abdus Samad
#  repo-actions: [edit, issue, source]
  
  open-graph: true
  
  twitter-card: true 
#  card-style: summary      
  
  site-url: "https://www.drabdus.info/"
  
  google-analytics:
    tracking-id: ""  # Please delete or replace with your own tracking ID
    anonymize-ip: true 

bibliography: references.bib  # Add references.bib to the root folder to enable the bibliography function

format:
  html:
    page-layout: full
    cache: true
    theme: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/\/drganghe\.github\.io\/custom'
    include-in-header: "files/includes/_academic.qmd"

